```mermaid
mindmap
  root((config.toml))
    log_level
    preshared_key
    [client]
      server_address
      server_port
      tun_name
      tun_ip
      tun_netmask
    [server]
      listen_address
      listen_port
```
