[global]
log_level = "info"
config_path = "config.docker.client.toml"

[client]
[client.tun]
name = "onebox0"
ip = "10.0.0.2"
netmask = "255.255.255.0"
mtu = 1500

[client.server]
address = "172.28.0.2:8080"
timeout = 30
keepalive = 60

[client.health]
probe_interval = 10
probe_timeout = 5
failure_threshold = 3

[client.auth]
psk = "dev-psk"
encryption = "ChaCha20Poly1305"

