# Simplified onebox-rs Configuration File
# This file contains the minimal configuration required by the SRS (SI-2).

log_level = "info"
preshared_key = "your-secure-pre-shared-key-here"

[client]
server_address = "198.51.100.1" # Public IP of the onebox-server
server_port = 51820

[server]
listen_address = "0.0.0.0" # Listen on all interfaces
listen_port = 51820
