direction: right

Users_LAN: {
  pc: 'PC / Laptop'
  onebox_client: 'onebox-client'
}

onebox_client_Device: {
  onebox_client -> TUNNEL
  TUNNEL -> 'WAN 1'
  TUNNEL -> 'WAN 2'
}

Public_Internet: {
  'WAN 1' -> 'onebox-server'
  'WAN 2' -> 'onebox-server'
}

Cloud_VPS: {
  'onebox-server' -> TUNNEL
  TUNNEL -> Internet
}

Users_LAN.pc -> Users_LAN.onebox_client
onebox_client_Device.onebox_client -> Public_Internet.'WAN 1'
onebox_client_Device.onebox_client -> Public_Internet.'WAN 2'
Public_Internet.'onebox-server' -> Cloud_VPS.TUNNEL
Cloud_VPS.TUNNEL -> Cloud_VPS.Internet

'onebox-client'.style.fill: "#f9f"
'onebox-server'.style.fill: "#ccf"
